version: '3.1'

services:
  db:
    image: mariadb:10.3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: a1s2d3f4
    volumes:
      - ./data/:/var/lib/mysql  
    ports: 
      - 3306:3306
    networks: 
      - mynet

  backend:
    image: node:18-alpine
    working_dir: /backend
    volumes:
      - ./backend:/backend
    ports:
      - 8080:8080
    command: npm run dev
    networks:
      - mynet

  frontend:
    image: node:18-alpine
    working_dir: /frontend
    volumes:
      - ./frontend:/frontend
    ports:
      - 5173:5173
    command: npm start
    networks:
      - mynet

networks:
  mynet:
